apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  networkType: OpenShiftSDN
  serviceNetwork: 
  - 172.30.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfOTYzMjdjYmZkMjZhNDA2OWFkNWY3NTc3YmU1ZTBmZTc6S0tGU1EzRFJDMDBHVVc4MjdBMkdBVkcyNU1STE5TVVUxVTRLMDdYMFpaU1lSTzgwVFhXM1k1UEpOMlNDM1hPNQ==","email":"rogermm@gmail.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfOTYzMjdjYmZkMjZhNDA2OWFkNWY3NTc3YmU1ZTBmZTc6S0tGU1EzRFJDMDBHVVc4MjdBMkdBVkcyNU1STE5TVVUxVTRLMDdYMFpaU1lSTzgwVFhXM1k1UEpOMlNDM1hPNQ==","email":"rogermm@gmail.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWM3OWMzMTY3LTZhZDAtNDI2YS04MWVlLTk1M2UzYmM2Yzc4NzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPV0V5TURZNU5tVm1OekEwTnpZeE9EQmlNbVExT0RFNFlXTTRORGc1T1NKOS5udDBGN2Vqei1YYjdaOFczZzVBWHJRUnRfQzVzUDkwcDMzSWtYOEJIVFgtQUF1dHF6N3FTSXl2NW5ydVBrdzhPRFpmVzJNREE2UE12SnJ0ZWZ1Z1psdXJsUlVPWkg3T0FCdDdTVHZlRVI3WElOWEloWjh5Y1dKWEl5SWl1ZXNaTk5wd1czVjQtQVdaSnBhOEp0dnJxNkpaRllsSGlOUi1WQUloQmJnbTJ0LU5kdDZNQm1SOWN2bEY4UVZ1SHVVaGtHZklzeFp0WlRGcEdxVUtSVUJLeDNXdDFWWkkwZkg0VHA0NUpzdDNGMUp3WDE5cmRram9hNDZ4TWhmbnZ6SlV0TzNwX2VNUkJkQnRJSGJRaVVsaU5HMElPSnhYUEVDV0F5ZENfR2l3MllmRkhmTlptWTVNUC1PeVZka2ZuX2dxVlFRT3ZTbEtCWlNwZkw5eW5uaF9GY056WVFsRGhEYW5acTFVcFZ2c2lvRHhKMWZrOHpHVXFoWXpyc0Joay1hYmRqQXFEWGd0Xy1BUHk0a1RtelVqbTB1aXF0QTlZOG82OW96bFEyWHhMVE43LUxMZXBCbXJnd0ltN0pFcVpRSG82WlhfSWcwbFBVOG5ucUVtVmdDZ3NVYm80SHRneWFKRmIxaEc5eTNLV3JsQzdxZ3FjcldyRWFZTnU5T3R1bkdmZkdqQkE2eFo0NzlpYkZVNllKM19ZX2tZRDNJUFlvaEtoZ1daUGdiaFVaalQ2WGNYY2dTWHpRR0FXUDVmVW5rcmQxUjJlM2R1c2JHOUFrY0dFakZUV2VWRmdmajU1QmhPZ0xVaGo4TUR3dlh0ZmtiUkdRNXV0QU1HeDhsOUpvQlpJaUEwZlBfX1JuNmN3cThMelk1N015WEdDa3NtWTlneW00SEpEQzZ0dU5LWQ==","email":"rogermm@gmail.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWM3OWMzMTY3LTZhZDAtNDI2YS04MWVlLTk1M2UzYmM2Yzc4NzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmtPV0V5TURZNU5tVm1OekEwTnpZeE9EQmlNbVExT0RFNFlXTTRORGc1T1NKOS5udDBGN2Vqei1YYjdaOFczZzVBWHJRUnRfQzVzUDkwcDMzSWtYOEJIVFgtQUF1dHF6N3FTSXl2NW5ydVBrdzhPRFpmVzJNREE2UE12SnJ0ZWZ1Z1psdXJsUlVPWkg3T0FCdDdTVHZlRVI3WElOWEloWjh5Y1dKWEl5SWl1ZXNaTk5wd1czVjQtQVdaSnBhOEp0dnJxNkpaRllsSGlOUi1WQUloQmJnbTJ0LU5kdDZNQm1SOWN2bEY4UVZ1SHVVaGtHZklzeFp0WlRGcEdxVUtSVUJLeDNXdDFWWkkwZkg0VHA0NUpzdDNGMUp3WDE5cmRram9hNDZ4TWhmbnZ6SlV0TzNwX2VNUkJkQnRJSGJRaVVsaU5HMElPSnhYUEVDV0F5ZENfR2l3MllmRkhmTlptWTVNUC1PeVZka2ZuX2dxVlFRT3ZTbEtCWlNwZkw5eW5uaF9GY056WVFsRGhEYW5acTFVcFZ2c2lvRHhKMWZrOHpHVXFoWXpyc0Joay1hYmRqQXFEWGd0Xy1BUHk0a1RtelVqbTB1aXF0QTlZOG82OW96bFEyWHhMVE43LUxMZXBCbXJnd0ltN0pFcVpRSG82WlhfSWcwbFBVOG5ucUVtVmdDZ3NVYm80SHRneWFKRmIxaEc5eTNLV3JsQzdxZ3FjcldyRWFZTnU5T3R1bkdmZkdqQkE2eFo0NzlpYkZVNllKM19ZX2tZRDNJUFlvaEtoZ1daUGdiaFVaalQ2WGNYY2dTWHpRR0FXUDVmVW5rcmQxUjJlM2R1c2JHOUFrY0dFakZUV2VWRmdmajU1QmhPZ0xVaGo4TUR3dlh0ZmtiUkdRNXV0QU1HeDhsOUpvQlpJaUEwZlBfX1JuNmN3cThMelk1N015WEdDa3NtWTlneW00SEpEQzZ0dU5LWQ==","email":"rogermm@gmail.com"}}}'

sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD4gU4fATz4o2TWf6TcqXiIshvB24Uk2ifzF0qZUNnKggwLk83NzNny2L1bWB7vlgDQJNzP22BB4756811yTSEtj34VZMuOGYiWkXcKiHyuAxRI0MlFOKveLr5P0NaE2pEloKIIIeF4+WoYhHS4OCYQHmILeDhXGPMwcaq/JZTBwyuXPN5NEwv0ibx1sYWFZwNlhinFp5kPEPEZZu8fMZVMaLrcegV84hYAs4gtOg2thlZmhyJi7jTORlyZ5v8FogK+86A6OQJPfNcF/7UP0wIbM9UZhsE8JJmqp9+liRMXffuJ6LR9PudSOOF28xxJ1JyUypDlG1aE2IzJNtDwKrKT rogermm@macos'
